export default {
  id: "biome-sample",
  name: "Biome Sample",
  version: "0.1.0",
  description: "Adds a custom biome with direct multi-noise placement.",
  onEnable(api) {
    api.biomes.register({
      id: "akivcraft.biome_sample:crystal_valley",
      temperature: 0.35,
      downfall: 0.55,
      hasPrecipitation: true,
      source: "overworld",
      skyColor: "#7ba4ff",
      fogColor: "#c5d5ff",
      waterFogColor: "#55ffff",
      waterColor: "#55ffff",
      grassColor: "#55ff80",
      foliageColor: "#40dd60",
      backgroundMusic: "minecraft:music.overworld.forest",
      noise: {
        temperature: [-0.45, -0.15],
        humidity: [0.2, 0.75],
        continentalness: [-0.2, 0.35],
        erosion: [-0.25, 0.25],
        depth: [-1.0, 1.0],
        weirdness: [-0.65, 0.65],
        offset: 0,
      },
      carvers: ["minecraft:cave", "minecraft:cave_extra_underground", "minecraft:canyon"],
      features: [
        [],
        ["minecraft:lake_lava_underground", "minecraft:lake_lava_surface"],
        ["minecraft:amethyst_geode"],
        ["minecraft:monster_room", "minecraft:monster_room_deep"],
        [],
        [],
        [
          "minecraft:ore_dirt", "minecraft:ore_gravel", "minecraft:ore_granite_upper", "minecraft:ore_granite_lower",
          "minecraft:ore_diorite_upper", "minecraft:ore_diorite_lower", "minecraft:ore_andesite_upper", "minecraft:ore_andesite_lower",
          "minecraft:ore_tuff", "minecraft:ore_coal_upper", "minecraft:ore_coal_lower", "minecraft:ore_iron_upper",
          "minecraft:ore_iron_middle", "minecraft:ore_iron_small", "minecraft:ore_gold", "minecraft:ore_gold_lower",
          "minecraft:ore_redstone", "minecraft:ore_redstone_lower", "minecraft:ore_diamond", "minecraft:ore_diamond_medium",
          "minecraft:ore_diamond_large", "minecraft:ore_diamond_buried", "minecraft:ore_lapis", "minecraft:ore_lapis_buried",
          "minecraft:ore_copper", "minecraft:underwater_magma", "minecraft:disk_sand", "minecraft:disk_clay", "minecraft:disk_gravel",
        ],
        [],
        ["minecraft:spring_water", "minecraft:spring_lava"],
        [
          "minecraft:glow_lichen", "minecraft:forest_flowers", "minecraft:trees_birch_and_oak_leaf_litter",
          "minecraft:flower_default", "minecraft:patch_grass_forest", "minecraft:brown_mushroom_normal",
          "minecraft:red_mushroom_normal", "minecraft:patch_pumpkin", "minecraft:patch_sugar_cane",
          "minecraft:patch_firefly_bush_near_water",
        ],
        ["minecraft:freeze_top_layer"],
      ],
      spawners: {
        ambient: [{ type: "minecraft:bat", minCount: 8, maxCount: 8, weight: 10 }],
        creature: [
          { type: "minecraft:sheep", minCount: 4, maxCount: 4, weight: 12 },
          { type: "minecraft:pig", minCount: 4, maxCount: 4, weight: 10 },
          { type: "minecraft:cow", minCount: 4, maxCount: 4, weight: 8 },
          { type: "minecraft:wolf", minCount: 4, maxCount: 4, weight: 5 },
        ],
        monster: [
          { type: "minecraft:spider", minCount: 4, maxCount: 4, weight: 100 },
          { type: "minecraft:zombie", minCount: 4, maxCount: 4, weight: 95 },
          { type: "minecraft:skeleton", minCount: 4, maxCount: 4, weight: 100 },
          { type: "minecraft:creeper", minCount: 4, maxCount: 4, weight: 100 },
          { type: "minecraft:enderman", minCount: 1, maxCount: 4, weight: 10 },
        ],
      },
    })
  },
}
